### ISSUE TITLE
[Internal Feat] Dependabot.yml

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/json-maestro#54]
We could possibly use dependabot to keep track of deps from requirements.txt etc`ve I've never done it with a python project but they say its possible.

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
```
