### ISSUE TITLE
[Bug] License attribution in pyproject.toml deprecated

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/json-maestro#62]
while running `python -m build`..

several times we see this warning

```shell

        ********************************************************************************
        Please consider removing the following classifiers in favor of a SPDX license expression:

        License :: OSI Approved :: MIT License

        See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
        ********************************************************************************
```

this needs to get fixed in our pyproject.toml, so we update this:

```toml
[project]
# Old:
# classifiers = ["License :: OSI Approved :: MIT License"]
# Replace with:
license = { text = "MIT" }
```

Then delete the line from the classifiers list:

"License :: OSI Approved :: MIT License",

this should fix this.
